[project]
name = "pythonic-integer"
version = "0.2.0"
description = "A class representing the mathematical concept of an integer using only the Python built-ins."
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
  "hypothesis",
  "more-itertools",
  "pytest",
  "ruff",
  "ipython>=8.12.3",
  "ipykernel>=6.29.5",
]
